### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by tfnico** [codingtwinky/atom-ungit#23]
Just got this deprecation message. Using Atom Version 0.182.0 (0.182.0) with atom-ungit 0.4.0:

atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.
```
Atom.Object.defineProperty.get (/Applications/Atom.app/Contents/Resources/app/src/atom.js:54:11)
Object.activate (/Users/tfnico/.atom/packages/atom-ungit/lib/atom-ungit.coffee:33:9)
```

**Comment by codingtwinky** [comment]
I think this was addressed in https://github.com/codingtwinky/atom-ungit/pull/19 and sorry I have been negligent in updating the package...  :P

Now, if you update `atom-ungit` it should be good now...

**Comment by tfnico** [comment]
@codingtwinky Thanks for looking into it. I just updated to atom-ugit 0.4.2, and the warning still appears.

Looking at https://github.com/codingtwinky/atom-ungit/blob/master/lib/atom-ungit.coffee#L33 - the deprecated method is still in use.

**Comment by codingtwinky** [comment]
Darn, I don't see that message in 0.187.0 atom with atom-ungit 0.4.2 so I assumed it was fixed by that PR.  But I do see below deprecation message and it is on my todo.

`Deprecation warning: moment construction falls back to js Date. This is discouraged and will be removed in upcoming major release. Please refer to https://github.com/moment/moment/issues/1407 for more info.`

**Comment by codingtwinky** [comment]
Found it!

I was looking at the wrong place.  Thanks!
